### ISSUE TITLE
distm_FUN for projections like UTM.

### ISSUE THREAD

**Issue by SeltaZheng** [morrowcj/remotePARTS#28]
My rasters are in UTM projection and the distance is Euclidean. I used rater::pointDistance to calculate it. 
I tried to use pointDistance for fitcor() but failed. 
Any suggestions on distance functions that will work for UTM?

Thank you.

**Comment by morrowcj** [comment]
remotePARTS cannot handle rasters natively. you need to convert it into a flat format (e.g., a matrix). 

Euclidean distances, or any other distances, can be used by simply passing a function that conforms to the following rules: 1) the first argument is a 2-column matrix of coordinates and 2) it returns a distance **matrix**. So for example the following function would work

```r
euc_dist <- function(coords){
    as.matrix(stats::dist(coords))
}
```

And you could then pass it to `fitCor` either by reference:

```r
fitCor(AR.map$residuals, coords, covar_FUN = "covar_exp", start = list(range = .1), distm_FUN = "euc_dist")
```
or inline:

```r
fitCor(AR.map$residuals, coords, covar_FUN = "covar_exp", start = list(range = .1), distm_FUN = function(x){as.matrix(dist(x))})
```
